version: '3.8'

services:
  postservice:
    build: .
    image: postservice:0.0.1
    ports:
      - 8081:8080
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/project_01
      - SPRING_REDIS_HOST=redis

  postgres:
    image: postgres:12.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: project_01
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - type: bind
        source: ./etc/init_db.sql
        target: /docker-entrypoint-initdb.d/init_db.sql
        read_only: true
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.8-alpine
    ports:
      - '6379:6379'

volumes:
 postgres_data:


