
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/exam
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
#      data-locations: classpath:static/db/*
      schema-locations: classpath:static/db/schema.sql
      mode: always
  application:
    name: onefit
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.xml
#    contexts: production, test, development
#    enabled: true


jwt:
  token:
    expiration:
      mills: 120000
    secret:
      key: tliBHq4zdrliA4e2MhdeIyua3m3LnvIQW56HkbaasC7aSz76WFcE+z0YtnvQPNXNocnSYifRL5ogcrLDFQIO0w==
bot:
  name: OneFit
  token: 7230181027:AAEC1YmxngpeAQfVfzvhElXG-807s_3vjH8
