spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: /
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


  sql:
    init:
      data-locations: classpath:static/db/data.sql
      schema-locations: classpath:static/db/schema.sql
      mode: never

jwt:
  token:
    expiration:
      mills: 120000
    secret:
      key: tliBHq4zdrliA4e2MhdeIyua3m3LnvIQW56HkbaasC7aSz76WFcE+z0YtnvQPNXNocnSYifRL5ogcrLDFQIO0w==
bot:
  name: OneFit
  token: 7230181027:AAEC1YmxngpeAQfVfzvhElXG-807s_3vjH8